# Write a program to store seven fruits in a list entered by the user

# fruits = [ 1,0,1045,"shyam","raju","vivek"]

fruits = []

f1= input("enter the friuts name ")
fruits.append(f1)
f2= input("enter the friuts name ")
fruits.append(f2)
f3= input("enter the friuts name ")
fruits.append(f3)
f4= input("enter the friuts name ")
fruits.append(f4)
f5= input("enter the friuts name ")
fruits.append(f5)
f6= input("enter the friuts name ")
fruits.append(f6)
f7= input("enter the friuts name ")
fruits.append(f7)
f8= input("enter the friuts name ")
fruits.append(f8)

print(fruits)