# Write a program to accept marks of 6 students and display them in a sorted manner.


marks = []

f1= int(input("enter the  marks here  "))
marks.append(f1)
f2= int(input("enter the  marks here  "))
marks.append(f2)
f3= int(input("enter the  marks here  "))
marks.append(f3)
f4= int(input("enter the  marks here  "))
marks.append(f4)
f5= int(input("enter the  marks here  "))
marks.append(f5)
f6= int(input("enter the  marks here  "))
marks.append(f6)
f7= int(input("enter the  marks here  "))
marks.append(f7)
f8= int(input("enter the  marks here  "))
marks.append(f8)


marks.sort()
print(marks)
